!function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e(require("react")):"function"==typeof define&&define.amd?define("react-components",["React"],e):"object"==typeof exports?exports["react-components"]=e(require("react")):t["react-components"]=e(t.React)}(window,function(t){return function(t){var e={};function n(r){if(e[r])return e[r].exports;var o=e[r]={i:r,l:!1,exports:{}};return t[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}return n.m=t,n.c=e,n.d=function(t,e,r){n.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:r})},n.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},n.t=function(t,e){if(1&e&&(t=n(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var o in t)n.d(r,o,function(e){return t[e]}.bind(null,o));return r},n.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return n.d(e,"a",e),e},n.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)},n.p="",n(n.s=473)}({0:function(e,n){e.exports=t},473:function(t,e,n){"use strict";n.r(e);var r=n(6),o=n(0),i=function(t){function e(e){var n=t.call(this,e)||this;return n.state={timer:"00:00"},n}return r.b(e,t),e.prototype.startInterval=function(t){var e=this;this.setState({timer:this.convertMStoTime(t)},function(){e.clearInterval(),e.innerInterval=setInterval(function(){t>0&&(t-=1e3,e.setState({timer:e.convertMStoTime(t)},function(){0===t&&(e.props.callback(),e.clearInterval())}))},1e3)})},e.prototype.clearInterval=function(){this.innerInterval&&(clearTimeout(this.innerInterval),this.innerInterval=null)},e.prototype.convertMStoTime=function(t){var e=new Date(t);return(e.getUTCHours()>0?e.getUTCHours()+":":"")+(e.getUTCMinutes()<10?"0"+e.getUTCMinutes():e.getUTCMinutes())+":"+(e.getUTCSeconds()<10?"0"+e.getUTCSeconds():e.getUTCSeconds())},e.prototype.componentDidMount=function(){null!==this.props.duration&&void 0!==this.props.duration&&this.startInterval(this.props.duration)},e.prototype.componentWillUnmount=function(){this.clearInterval()},e.prototype.componentDidUpdate=function(t){t.duration!==this.props.duration&&null!==this.props.duration&&void 0!==this.props.duration&&this.startInterval(this.props.duration)},e.prototype.render=function(){return o.createElement("div",{className:"custom-timer"+(this.props.className?" "+this.props.className:"")},this.state.timer)},e}(o.Component);n.d(e,"Timer",function(){return i})},6:function(t,e,n){"use strict";n.d(e,"b",function(){return o}),n.d(e,"a",function(){return i});
/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */
var r=function(t,e){return(r=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var n in e)e.hasOwnProperty(n)&&(t[n]=e[n])})(t,e)};function o(t,e){function n(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(n.prototype=e.prototype,new n)}var i=function(){return(i=Object.assign||function(t){for(var e,n=1,r=arguments.length;n<r;n++)for(var o in e=arguments[n])Object.prototype.hasOwnProperty.call(e,o)&&(t[o]=e[o]);return t}).apply(this,arguments)}}})});